repos:
  - repo: local
    hooks:
      - id: print-message
        name: Print Message
        entry: echo "Running pre-commit checks..."
        language: system
        stages: [pre-commit]

      - id: run-haskell-tests
        name: Run Haskell Tests
        entry: stack test
        language: system
        stages: [pre-commit]
        pass_filenames: false
