repos:
  - repo: local
    hooks:
      - id: run-lisp-tests
        name: Run Haskell Lisp-only Tests
        entry: stack test --test-arguments="--only-lisp"
        language: system
        stages: [pre-commit]
        pass_filenames: false

      - id: cleanup-project
        name: Clean Up Project
        entry: bash -c 'make fclean && rm -f glados-test.tix && stack clean'
        language: system
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
